# Generated by Django 3.0.8 on 2020-07-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200723_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
