# Generated by Django 3.0.8 on 2020-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_bid',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
