# Generated by Django 3.0.8 on 2020-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200801_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
