# Generated by Django 3.0.8 on 2020-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
