# Generated by Django 3.0.8 on 2020-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='catelog',
            field=models.CharField(blank=True, choices=[('Household', 'Household'), ('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Other', 'Other')], max_length=15),
        ),
    ]
